"""Scene-adaptive helpers exposed as part of the package surface."""

from enhance_video.pipeline import (
    GuardrailCandidate,
    RuntimeEstimate,
    SceneAdaptiveResult,
    ScenePlanEntry,
    build_guardrail_candidates,
    build_scene_adaptive_candidates,
    build_scene_ranges,
    build_scene_texture_scores,
    compute_scene_texture_raw,
    detect_scene_boundaries,
    estimate_candidate_runtime,
    estimate_candidate_runtime_for_frames,
    get_texture_weight,
    normalize_scores,
    plan_scene_adaptive_strategy,
    render_scene_chunk,
    run_upscale_scene_adaptive,
    select_sample_frames,
    select_scene_candidate_by_projection,
    serialize_scene_plan,
)

__all__ = [
    "GuardrailCandidate",
    "RuntimeEstimate",
    "SceneAdaptiveResult",
    "ScenePlanEntry",
    "build_guardrail_candidates",
    "build_scene_adaptive_candidates",
    "build_scene_ranges",
    "build_scene_texture_scores",
    "compute_scene_texture_raw",
    "detect_scene_boundaries",
    "estimate_candidate_runtime",
    "estimate_candidate_runtime_for_frames",
    "get_texture_weight",
    "normalize_scores",
    "plan_scene_adaptive_strategy",
    "render_scene_chunk",
    "run_upscale_scene_adaptive",
    "select_sample_frames",
    "select_scene_candidate_by_projection",
    "serialize_scene_plan",
]
